#                           --------------- la base calendar.csv---------------

In [ ]:
! pip install -q kaggle

In [ ]:
! kaggle datasets download konradb/inside-airbnb-usa

Dataset URL: https://www.kaggle.com/datasets/konradb/inside-airbnb-usa
License(s): Attribution 4.0 International (CC BY 4.0)
Downloading inside-airbnb-usa.zip to /content
100% 1.63G/1.64G [00:22<00:00, 67.9MB/s]
100% 1.64G/1.64G [00:23<00:00, 76.3MB/s]

In [ ]:
! unzip inside-airbnb-usa.zip

Archive:  inside-airbnb-usa.zip
  inflating: usa/Asheville/calendar.csv
  inflating: usa/Asheville/listings.csv
  inflating: usa/Asheville/listings_detailed.csv
  inflating: usa/Asheville/neighbourhoods.csv
  inflating: usa/Asheville/neighbourhoods.geojson
  inflating: usa/Asheville/reviews.csv
  inflating: usa/Asheville/reviews_detailed.csv
  inflating: usa/Austin/calendar.csv
  inflating: usa/Austin/listings.csv
  inflating: usa/Austin/listings_detailed.csv
  inflating: usa/Austin/neighbourhoods.csv
  inflating: usa/Austin/neighbourhoods.geojson
  inflating: usa/Austin/reviews.csv
  inflating: usa/Austin/reviews_detailed.csv
  inflating: usa/Bozeman/calendar.csv
  inflating: usa/Bozeman/listings.csv
  inflating: usa/Bozeman/listings_detailed.csv
  inflating: usa/Bozeman/neighbourhoods.csv
  inflating: usa/Bozeman/neighbourhoods.geojson
  inflating: usa/Bozeman/reviews.csv
  inflating: usa/Bozeman/reviews_detailed.csv
  inflating: usa/Broward County/calendar.csv
  inflating: usa/Broward County/listings.csv
  inflating: usa/Broward County/listings_detailed.csv
  inflating: usa/Broward County/neighbourhoods.csv
  inflating: usa/Broward County/neighbourhoods.geojson
  inflating: usa/Broward County/reviews.csv
  inflating: usa/Broward County/reviews_detailed.csv
  inflating: usa/Cambridge/calendar.csv
  inflating: usa/Cambridge/listings.csv
  inflating: usa/Cambridge/listings_detailed.csv
  inflating: usa/Cambridge/neighbourhoods.csv
  inflating: usa/Cambridge/neighbourhoods.geojson
  inflating: usa/Cambridge/reviews.csv
  inflating: usa/Cambridge/reviews_detailed.csv
  inflating: usa/Chicago/calendar.csv
  inflating: usa/Chicago/listings.csv
  inflating: usa/Chicago/listings_detailed.csv
  inflating: usa/Chicago/neighbourhoods.csv
  inflating: usa/Chicago/neighbourhoods.geojson
  inflating: usa/Chicago/reviews.csv
  inflating: usa/Chicago/reviews_detailed.csv
  inflating: usa/Clark County NV/calendar.csv
  inflating: usa/Clark County NV/listings.csv
  inflating: usa/Clark County NV/listings_detailed.csv
  inflating: usa/Clark County NV/neighbourhoods.csv
  inflating: usa/Clark County NV/neighbourhoods.geojson
  inflating: usa/Clark County NV/reviews.csv
  inflating: usa/Clark County NV/reviews_detailed.csv
  inflating: usa/Columbus/calendar.csv
  inflating: usa/Columbus/listings.csv
  inflating: usa/Columbus/listings_detailed.csv
  inflating: usa/Columbus/neighbourhoods.csv
  inflating: usa/Columbus/neighbourhoods.geojson
  inflating: usa/Columbus/reviews.csv
  inflating: usa/Columbus/reviews_detailed.csv
  inflating: usa/Dallas/calendar.csv
  inflating: usa/Dallas/listings.csv
  inflating: usa/Dallas/listings_detailed.csv
  inflating: usa/Dallas/neighbourhoods.csv
  inflating: usa/Dallas/neighbourhoods.geojson
  inflating: usa/Dallas/reviews.csv
  inflating: usa/Dallas/reviews_detailed.csv
  inflating: usa/Denver/calendar.csv
  inflating: usa/Denver/listings.csv
  inflating: usa/Denver/listings_detailed.csv
  inflating: usa/Denver/neighbourhoods.csv
  inflating: usa/Denver/neighbourhoods.geojson
  inflating: usa/Denver/reviews.csv
  inflating: usa/Denver/reviews_detailed.csv
  inflating: usa/Fort Worth/calendar.csv
  inflating: usa/Fort Worth/listings.csv
  inflating: usa/Fort Worth/listings_detailed.csv
  inflating: usa/Fort Worth/neighbourhoods.csv
  inflating: usa/Fort Worth/neighbourhoods.geojson
  inflating: usa/Fort Worth/reviews.csv
  inflating: usa/Fort Worth/reviews_detailed.csv
  inflating: usa/Hawaii/calendar.csv
  inflating: usa/Hawaii/listings.csv
  inflating: usa/Hawaii/listings_detailed.csv
  inflating: usa/Hawaii/neighbourhoods.csv
  inflating: usa/Hawaii/neighbourhoods.geojson
  inflating: usa/Hawaii/reviews.csv
  inflating: usa/Hawaii/reviews_detailed.csv
  inflating: usa/Jersey City/calendar.csv
  inflating: usa/Jersey City/listings.csv
  inflating: usa/Jersey City/listings_detailed.csv
  inflating: usa/Jersey City/neighbourhoods.csv
  inflating: usa/Jersey City/neighbourhoods.geojson
  inflating: usa/Jersey City/reviews.csv
  inflating: usa/Jersey City/reviews_detailed.csv
  inflating: usa/Los Angeles/calendar.csv
  inflating: usa/Los Angeles/listings.csv
  inflating: usa/Los Angeles/listings_detailed.csv
  inflating: usa/Los Angeles/neighbourhoods.csv
  inflating: usa/Los Angeles/neighbourhoods.geojson
  inflating: usa/Los Angeles/reviews.csv
  inflating: usa/Los Angeles/reviews_detailed.csv
  inflating: usa/Nashville/calendar.csv
  inflating: usa/Nashville/listings.csv
  inflating: usa/Nashville/listings_detailed.csv
  inflating: usa/Nashville/neighbourhoods.csv
  inflating: usa/Nashville/neighbourhoods.geojson
  inflating: usa/Nashville/reviews.csv
  inflating: usa/Nashville/reviews_detailed.csv
  inflating: usa/New Orleans/calendar.csv
  inflating: usa/New Orleans/listings.csv
  inflating: usa/New Orleans/listings_detailed.csv
  inflating: usa/New Orleans/neighbourhoods.csv
  inflating: usa/New Orleans/neighbourhoods.geojson
  inflating: usa/New Orleans/reviews.csv
  inflating: usa/New Orleans/reviews_detailed.csv
  inflating: usa/New York City/calendar.csv
  inflating: usa/New York City/listings.csv
  inflating: usa/New York City/listings_detailed.csv
  inflating: usa/New York City/neighbourhoods.csv
  inflating: usa/New York City/neighbourhoods.geojson
  inflating: usa/New York City/reviews.csv
  inflating: usa/New York City/reviews_detailed.csv
  inflating: usa/Newark/calendar.csv
  inflating: usa/Newark/listings.csv
  inflating: usa/Newark/listings_detailed.csv
  inflating: usa/Newark/neighbourhoods.csv
  inflating: usa/Newark/neighbourhoods.geojson
  inflating: usa/Newark/reviews.csv
  inflating: usa/Newark/reviews_detailed.csv
  inflating: usa/Oakland/calendar.csv
  inflating: usa/Oakland/listings.csv
  inflating: usa/Oakland/listings_detailed.csv
  inflating: usa/Oakland/neighbourhoods.csv
  inflating: usa/Oakland/neighbourhoods.geojson
  inflating: usa/Oakland/reviews.csv
  inflating: usa/Oakland/reviews_detailed.csv
  inflating: usa/Pacific Grove/calendar.csv
  inflating: usa/Pacific Grove/listings.csv
  inflating: usa/Pacific Grove/listings_detailed.csv
  inflating: usa/Pacific Grove/neighbourhoods.csv
  inflating: usa/Pacific Grove/neighbourhoods.geojson
  inflating: usa/Pacific Grove/reviews.csv
  inflating: usa/Pacific Grove/reviews_detailed.csv
  inflating: usa/Portland/calendar.csv
  inflating: usa/Portland/listings.csv
  inflating: usa/Portland/listings_detailed.csv
  inflating: usa/Portland/neighbourhoods.csv
  inflating: usa/Portland/neighbourhoods.geojson
  inflating: usa/Portland/reviews.csv
  inflating: usa/Portland/reviews_detailed.csv
  inflating: usa/Rhode Island/calendar.csv
  inflating: usa/Rhode Island/listings.csv
  inflating: usa/Rhode Island/listings_detailed.csv
  inflating: usa/Rhode Island/neighbourhoods.csv
  inflating: usa/Rhode Island/neighbourhoods.geojson
  inflating: usa/Rhode Island/reviews.csv
  inflating: usa/Rhode Island/reviews_detailed.csv
  inflating: usa/Salem/calendar.csv
  inflating: usa/Salem/listings.csv
  inflating: usa/Salem/listings_detailed.csv
  inflating: usa/Salem/neighbourhoods.csv
  inflating: usa/Salem/neighbourhoods.geojson
  inflating: usa/Salem/reviews.csv
  inflating: usa/Salem/reviews_detailed.csv
  inflating: usa/San Diego/calendar.csv
  inflating: usa/San Diego/listings.csv
  inflating: usa/San Diego/listings_detailed.csv
  inflating: usa/San Diego/neighbourhoods.csv
  inflating: usa/San Diego/neighbourhoods.geojson
  inflating: usa/San Diego/reviews.csv
  inflating: usa/San Diego/reviews_detailed.csv
  inflating: usa/San Francisco/calendar.csv
  inflating: usa/San Francisco/listings.csv
  inflating: usa/San Francisco/listings_detailed.csv
  inflating: usa/San Francisco/neighbourhoods.csv
  inflating: usa/San Francisco/neighbourhoods.geojson
  inflating: usa/San Francisco/reviews.csv
  inflating: usa/San Francisco/reviews_detailed.csv
  inflating: usa/San Mateo County/calendar.csv
  inflating: usa/San Mateo County/listings.csv
  inflating: usa/San Mateo County/listings_detailed.csv
  inflating: usa/San Mateo County/neighbourhoods.csv
  inflating: usa/San Mateo County/neighbourhoods.geojson
  inflating: usa/San Mateo County/reviews.csv
  inflating: usa/San Mateo County/reviews_detailed.csv
  inflating: usa/Santa Clara County/calendar.csv
  inflating: usa/Santa Clara County/listings.csv
  inflating: usa/Santa Clara County/listings_detailed.csv
  inflating: usa/Santa Clara County/neighbourhoods.csv
  inflating: usa/Santa Clara County/neighbourhoods.geojson
  inflating: usa/Santa Clara County/reviews.csv
  inflating: usa/Santa Clara County/reviews_detailed.csv
  inflating: usa/Santa Cruz County /calendar.csv
  inflating: usa/Santa Cruz County /listings.csv
  inflating: usa/Santa Cruz County /listings_detailed.csv
  inflating: usa/Santa Cruz County /neighbourhoods.csv
  inflating: usa/Santa Cruz County /neighbourhoods.geojson
  inflating: usa/Santa Cruz County /reviews.csv
  inflating: usa/Santa Cruz County /reviews_detailed.csv
  inflating: usa/Seattle/calendar.csv
  inflating: usa/Seattle/listings.csv
  inflating: usa/Seattle/listings_detailed.csv
  inflating: usa/Seattle/neighbourhoods.csv
  inflating: usa/Seattle/neighbourhoods.geojson
  inflating: usa/Seattle/reviews.csv
  inflating: usa/Seattle/reviews_detailed.csv
  inflating: usa/Twin Cities MSA/calendar.csv
  inflating: usa/Twin Cities MSA/listings.csv
  inflating: usa/Twin Cities MSA/listings_detailed.csv
  inflating: usa/Twin Cities MSA/neighbourhoods.csv
  inflating: usa/Twin Cities MSA/neighbourhoods.geojson
  inflating: usa/Twin Cities MSA/reviews.csv
  inflating: usa/Twin Cities MSA/reviews_detailed.csv
  inflating: usa/Washington DC/calendar.csv
  inflating: usa/Washington DC/listings.csv
  inflating: usa/Washington DC/listings_detailed.csv
  inflating: usa/Washington DC/neighbourhoods.csv
  inflating: usa/Washington DC/neighbourhoods.geojson
  inflating: usa/Washington DC/reviews.csv
  inflating: usa/Washington DC/reviews_detailed.csv

In [ ]:
import pandas as pd

file_path = '/content/calendar.csv.zip'
calendar_data = pd.read_csv(file_path)


print(calendar_data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 105120 entries, 0 to 105119
Data columns (total 7 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   listing_id      105120 non-null  int64
 1   date            105120 non-null  object
 2   available       105120 non-null  object
 3   price           105120 non-null  object
 4   adjusted_price  105120 non-null  object
 5   minimum_nights  105119 non-null  float64
 6   maximum_nights  105119 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 5.6+ MB
None

# Suppression des symboles et conversion en type float

In [ ]:
calendar_data['price'] = (
    calendar_data['price'].str.replace('[\$,]', '', regex=True).astype(float)
)
calendar_data['adjusted_price'] = (
    calendar_data['adjusted_price'].str.replace('[\$,]', '', regex=True).astype(float)
)

 # Conversion de la colonne date en format datetime

In [ ]:
calendar_data['date'] = pd.to_datetime(calendar_data['date'], errors='coerce')

#  Conversion des colonnes minimum_nights et maximum_nights en entiers

In [ ]:
calendar_data['minimum_nights'] = calendar_data['minimum_nights'].fillna(0).astype(int)
calendar_data['maximum_nights'] = calendar_data['maximum_nights'].fillna(0).astype(int)

 # Nettoyage des colonnes booléennes

# Conversion de la colonne available en booléen (True/False)

In [ ]:
calendar_data['available'] = calendar_data['available'].map({'t': True, 'f': False})

# Vérifier les données nettoyées

In [ ]:
calendar_data.head(), calendar_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 105120 entries, 0 to 105119
Data columns (total 7 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   listing_id      105120 non-null  int64
 1   date            105120 non-null  datetime64[ns]
 2   available       105120 non-null  bool
 3   price           105120 non-null  float64
 4   adjusted_price  105120 non-null  float64
 5   minimum_nights  105120 non-null  int64
 6   maximum_nights  105120 non-null  int64
dtypes: bool(1), datetime64[ns](1), float64(2), int64(3)
memory usage: 4.9 MB

(   listing_id       date  available  price  adjusted_price  minimum_nights  \
 0      199568 2023-03-27      False   95.0            95.0               3
 1      199568 2023-03-28      False   95.0            95.0               3
 2      199568 2023-03-29      False   95.0            95.0               3
 3      199568 2023-03-30      False   95.0            95.0               3
 4      199568 2023-03-31      False   95.0            95.0               3

    maximum_nights
 0             100
 1             100
 2             100
 3             100
 4             100  ,
 None)

#                           --------------- la base listing ---------------

In [ ]:
import pandas as pd

file_path = '/content/listings.csv'
listings = pd.read_csv(file_path)


print(listings.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 288 entries, 0 to 287
Data columns (total 18 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              288 non-null    int64
 1   name                            288 non-null    object
 2   host_id                         288 non-null    int64
 3   host_name                       288 non-null    object
 4   neighbourhood_group             0 non-null      float64
 5   neighbourhood                   288 non-null    object
 6   latitude                        288 non-null    float64
 7   longitude                       288 non-null    float64
 8   room_type                       288 non-null    object
 9   price                           288 non-null    int64
 10  minimum_nights                  288 non-null    int64
 11  number_of_reviews               288 non-null    int64
 12  last_review                     241 non-null    object
 13  reviews_per_month               241 non-null    float64
 14  calculated_host_listings_count  288 non-null    int64
 15  availability_365                288 non-null    int64
 16  number_of_reviews_ltm           288 non-null    int64
 17  license                         0 non-null      float64
dtypes: float64(5), int64(8), object(5)
memory usage: 40.6+ KB
None

In [ ]:
listings.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
0,199568,Garden studio apt,974919,Sara,NaN,Ward 1,44.95196,-123.05627,Entire home/apt,95,3,192,2023-01-30,1.36,1,58,19,NaN
1,5021839,Southtown Cottage,25909376,Sean,NaN,Ward 7,44.91029,-123.04691,Entire home/apt,120,3,3,2023-03-24,0.85,1,8,3,NaN
2,7293821,Chauffeurs Room @ the Villa,38202007,Julie,NaN,Ward 7,44.92484,-123.04990,Entire home/apt,105,2,387,2023-03-18,4.13,1,70,28,NaN
3,8524259,Single room in Comfort Home,2421461,Nancy,NaN,Ward 7,44.89105,-123.06843,Private room,65,1,3,2021-04-21,0.04,2,296,0,NaN
4,8698684,Charming 1925 Craftsman centrally located!,3208932,Christy,NaN,Ward 2,44.93305,-123.01985,Entire home/apt,225,3,89,2023-01-01,1.01,3,0,8,NaN

# [texte du lien](https://) Supprimer les colonnes inutiles

In [ ]:
listings= listings.drop(columns=["neighbourhood_group", "license"])

KeyError: "['neighbourhood_group', 'license'] not found in axis"